Repository kibis-is/web-extension, pull requests merged in 2023-11, with the labels that each got.

#22 feat: update webpack config to chunk node modules
  webpack/webpack.common.config.ts
  webpack/webpack.config.ts
Labels: 🏗️ build, 👩🏽‍💻 developer experience

#23 build: add firefox add-on linting
  .github/actions/use-dependencies/action.yml
  .github/workflows/lint_build_test.yml
  .github/workflows/pull_request_checks.yml
  package.json
  webpack/webpack.config.ts
  yarn.lock
Labels: 🏗️ build, 📦 dependencies

#25 fix: manifest version not being updated
  .github/workflows/release.yml
  .releaserc
  bin/update_manifest_version.sh
  src/manifest.common.json
Labels: 🏗️ build, 🐛 bug

#26 docs: add issue template chooser
  .github/ISSUE_TEMPLATE/bug_report_template.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request_template.yml
  .github/actions/install-yq/action.yml
  .github/workflows/release.yml
  .releaserc
  bin/update_issue_templates.sh
Labels: 🏗️ build, 📝 documentation

#27 feat: tighten permissions
  README.md
  __mocks__/webextension-polyfill.ts
  package.json
  src/@types/global/index.d.ts
  src/extension/hooks/useOnNetworkConnectivity/useOnNetworkConnectivity.ts
  src/extension/pages/AssetPage/AssetPage.tsx
  src/extension/theme/theme.tsx
  src/manifest.chrome.json
  src/manifest.common.json
  test/setup.ts
  webpack/webpack.config.ts
  yarn.lock
Labels: ♻️ refactor, 🐛 bug, 📝 documentation, 📦 dependencies

#29 fix: content scripts reply on modules
  dapp/App.tsx
  dapp/index.ts
  package.json
  src/@types/assets/index.d.ts
  src/@types/styles/index.d.ts
  src/extension/apps/background/index.ts
  src/extension/apps/main/index.ts
  src/extension/apps/registration/index.ts
  src/extension/components/Fonts/Fonts.tsx
  src/extension/components/Fonts/index.ts
  src/extension/components/ThemeProvider/ThemeProvider.tsx
  src/extension/services/BackgroundService.ts
  src/extension/styles/fonts.css
  tsconfig.json
  webpack/constants/Names.ts
  webpack/constants/index.ts
  webpack/enums/ConfigNameEnum.ts
  webpack/enums/TargetEnum.ts
  webpack/enums/index.ts
  webpack/plugins/ManifestBuilderPlugin/ManifestBuilderPlugin.ts
  webpack/plugins/WebExtPlugin/WebExtPlugin.ts
  webpack/plugins/WebExtPlugin/types/IOptions.ts
  webpack/types/IAfterEmitHookFunction.ts
  webpack/types/ICompilationHookFunction.ts
  webpack/types/IDoneHookFunction.ts
  webpack/types/ITargetType.ts
  webpack/types/IWebpackEnvironmentVariables.ts
  webpack/types/index.ts
  webpack/utils/createCommonConfig.ts
  webpack/webpack.config.ts
  yarn.lock
Labels: ♻️ refactor, 🏗️ build, 🐛 bug, 📦 dependencies

#30 feat: remove purestake block explorer and algod api
  src/extension/config/networks.ts
Labels: ♻️ refactor

#31 fix: voitest-v1 config
  dapp/App.tsx
  src/extension/config/networks.ts
Labels: 🐛 bug

#36 feat: use testnet by default and add settings option to allow mainnet
  src/extension/components/CreatePasswordInput/CreatePasswordInput.tsx
  src/extension/components/SettingsSelectItem/SettingsSelectItem.tsx
  src/extension/components/SettingsSubHeading/SettingsSubHeading.tsx
  src/extension/components/SettingsSwitchItem/SettingsSwitchItem.tsx
  src/extension/components/Warning/Warning.tsx
  src/extension/features/settings/thunks/setSettings.ts
  src/extension/features/settings/utils/createDefaultSettings.ts
  src/extension/features/settings/utils/getInitialState.ts
  src/extension/pages/AdvancedSettingsPage/AdvancedSettingsPage.tsx
  src/extension/pages/ChangePasswordPage/ChangePasswordPage.tsx
  src/extension/pages/CreateNewAccountPage/CreateNewAccountPage.tsx
  src/extension/pages/CreatePasswordPage/CreatePasswordPage.tsx
  src/extension/pages/GeneralSettingsPage/GeneralSettingsPage.tsx
  src/extension/selectors/useSelectNetworks.ts
  src/extension/translations/en.ts
  src/extension/types/IAdvancedSettings.ts
  src/extension/utils/selectDefaultNetwork.ts
Labels: ♻️ refactor, ✨ feature
