Repository kibis-is/web-extension, pull requests merged in 2024-01, with the labels that each got.

#94 feat: pressing the enter key submits forms
  src/extension/components/CreatePasswordInput/CreatePasswordInput.tsx
  src/extension/components/PasswordInput/PasswordInput.tsx
  src/extension/modals/AddAssetModal/AddAssetModal.tsx
  src/extension/modals/ConfirmPasswordModal/ConfirmPasswordModal.tsx
  src/extension/modals/SendAssetModal/SendAssetModal.tsx
  src/extension/modals/SignBytesModal/SignBytesContentSkeleton.tsx
  src/extension/modals/SignBytesModal/SignBytesModal.tsx
  src/extension/modals/SignTxnsModal/SignTxnsModal.tsx
  src/extension/pages/CreatePasswordPage/CreatePasswordPage.tsx
  src/extension/selectors/index.ts
  src/extension/selectors/useSelectRegistrationPassword.ts
  src/extension/selectors/useSelectRegistrationScore.ts
Labels: ✨ feature

#96 ci: chrome publish automation not working
  .github/workflows/publish_to_chrome_web_store.yml
  .github/workflows/refresh_chrome_web_store_token.yml
  bin/publish_to_chrome.sh
  bin/refresh_chrome_web_store_token.sh
Labels: 🏗️ build

#98 feat: remove the walletconnect scanning button from the sidebar
  src/extension/components/SideBar/SideBar.tsx
Labels: ✨ feature

#101 build: add edge build
  .github/workflows/publish_to_chrome_web_store.yml
  .github/workflows/pull_request_checks.yml
  .github/workflows/release.yml
  .gitignore
  .releaserc
  bin/package.sh
  bin/publish_to_chrome_web_store.sh
  package.json
  src/manifest.firefox.json
  src/manifest.v2.json
  src/manifest.v3.json
  webpack/constants/Directories.ts
  webpack/enums/TargetEnum.ts
  webpack/plugins/WebExtPlugin/WebExtPlugin.ts
  webpack/webpack.config.ts
Labels: 🏗️ build

#107 feat: move strong password policy as link to website
  package.json
  src/documents/strong_password_policy/en.md
  src/extension/components/CreatePasswordInput/CreatePasswordInput.tsx
  src/extension/constants/Links.ts
  src/extension/modals/DocumentModal/DocumentModal.tsx
  src/extension/modals/DocumentModal/hooks/useDocument/index.ts
  src/extension/modals/DocumentModal/hooks/useDocument/types/IDocument.ts
  src/extension/modals/DocumentModal/hooks/useDocument/types/IUseDocumentState.ts
  src/extension/modals/DocumentModal/hooks/useDocument/types/index.ts
  src/extension/modals/DocumentModal/hooks/useDocument/useDocument.ts
  src/extension/modals/DocumentModal/index.ts
  src/extension/modals/DocumentModal/utils/createComponents.tsx
  src/extension/modals/DocumentModal/utils/index.ts
  webpack/webpack.config.ts
  yarn.lock
Labels: ✨ feature, 🏗️ build, 📦 dependencies

#115 refactor: remove unused downloads permission
  README.md
  src/manifest.v2.json
  src/manifest.v3.json
Labels: ♻️ refactor, 📝 documentation

#116 feat: add pera explorer to algorand mainnet and testnet
  src/extension/config/networks.ts
Labels: ✨ feature

#121 build: remove auto install of dev browsers
  README.md
  bin/install_chrome.sh
  bin/install_firefox.sh
  bin/post_install.sh
  package.json
Labels: 🏗️ build, 📝 documentation

#122 build(yarn): use prepare for postinstall script
  package.json
Labels: 🏗️ build

#123 ci: automatically upload sign and publish to the firefox store
  .github/actions/publish-firefox-add-ons/action.yml
  .github/actions/publish-firefox-add-ons/index.mjs
  .github/actions/publish-firefox-add-ons/package.json
  .github/actions/publish-firefox-add-ons/utils.mjs
  .github/actions/publish-firefox-add-ons/yarn.lock
  .github/workflows/publish.yml
  .github/workflows/pull_request_checks.yml
  .github/workflows/release.yml
Labels: 🏗️ build, 🌐 firefox

#125 docs: firefox add on link in readme
  README.md
Labels: 📝 documentation

#127 fix: scanning for qr code in walletconnect runs forever once initiated
  src/extension/constants/Durations.ts
  src/extension/hooks/useCaptureQrCode/index.ts
  src/extension/hooks/useCaptureQrCode/types/IUseCaptureQrCodeState.ts
  src/extension/hooks/useCaptureQrCode/types/index.ts
  src/extension/hooks/useCaptureQrCode/useCaptureQrCode.ts
  src/extension/hooks/useCaptureQrCode/utils/captureQrCode.ts
  src/extension/hooks/useCaptureQrCode/utils/index.ts
  src/extension/hooks/useWalletConnect/useWalletConnect.ts
  src/extension/modals/WalletConnectModal/WalletConnectModal.tsx
  src/extension/modals/WalletConnectModal/hooks/useCaptureQrCode/useCaptureQrCode.ts
Labels: ♻️ refactor, 🐛 bug

#130 fix: replace arc0013 references with correct arc0027
  src/common/enums/Arc0027MessageReferenceEnum.ts
Labels: 🐛 bug

#133 fix: use settings to filter supported networks
  src/extension/services/BackgroundMessageHandler/BackgroundMessageHandler.ts
  src/extension/utils/fetchSupportedNetworks/fetchSupportedNetworks.ts
  src/extension/utils/fetchSupportedNetworks/index.ts
  src/extension/utils/isNetworkSupported/index.ts
  src/extension/utils/isNetworkSupported/isNetworkSupported.ts
  src/external/services/ExternalMessageBroker/ExternalMessageBroker.ts
Labels: 🐛 bug

#134 fix: mainnet checked state correctly passed to settings update
  src/extension/components/SettingsSelectItem/SettingsSelectItem.tsx
  src/extension/features/settings/thunks/saveSettingsToStorage.ts
  src/extension/pages/AdvancedSettingsPage/AdvancedSettingsPage.tsx
Labels: 🐛 bug

#135 fix: correct references to copy application id tooltip label
  src/extension/modals/AddAssetModal/AddAssetModalArc200AssetSummaryContent.tsx
  src/extension/pages/AssetPage/AssetPage.tsx
Labels: 🐛 bug

#137 build: use the github_workspace env var to determine zip file path
  .github/actions/publish-to-chrome-web-store/index.ts
  .github/actions/publish-to-chrome-web-store/package.json
  .github/actions/publish-to-chrome-web-store/yarn.lock
  .github/actions/publish-to-firefox-add-ons/index.ts
  .github/actions/publish-to-firefox-add-ons/package.json
  .github/actions/publish-to-firefox-add-ons/yarn.lock
  .github/actions/publish-to-microsoft-edge-add-ons/index.ts
  .github/actions/publish-to-microsoft-edge-add-ons/package.json
  .github/actions/publish-to-microsoft-edge-add-ons/yarn.lock
Labels: 🏗️ build

#142 fix: allow for comma separated seed phrases
  src/extension/components/EnterMnemonicPhraseInput/EnterMnemonicPhraseInput.tsx
  src/extension/components/EnterMnemonicPhraseInput/utils/index.ts
  src/extension/components/EnterMnemonicPhraseInput/utils/isPhrasesEmpty.ts
  src/extension/translations/en.ts
Labels: ✨ feature, 🐛 bug

#140 fix: change label for "remove asset" to "hide asset"
  src/extension/pages/AssetPage/AssetPage.tsx
  src/extension/translations/en.ts
Labels: 🐛 bug

#145 ci: set explicit node version in ci/cd pipelines
  .github/actions/publish-to-chrome-web-store/action.yml
  .github/actions/publish-to-firefox-add-ons/action.yml
  .github/actions/publish-to-microsoft-edge-add-ons/action.yml
  .github/actions/use-dependencies/action.yml
  .github/workflows/publish.yml
  .github/workflows/pull_request_checks.yml
  .github/workflows/refresh_chrome_web_store_token.yml
  .github/workflows/release.yml
Labels: 🏗️ build
